### ISSUE TITLE
刚刚发现你的64位校验错误

### ISSUE THREAD

**Issue by ruan421** [tkzcfc/net_uv#2]

**Comment by tkzcfc** [comment]
你好，请问代码是最新的嘛？我记得这个bug我改过了

**Comment by ruan421** [comment]
嗯，看到你的注释了发自我的华为手机-------- 原始邮件 --------主题：Re: [tkzcfc/net_uv] 刚刚发现你的64位校验错误 (#2)发件人：tkzcfc 收件人：tkzcfc/net_uv 抄送：ruan421 ,Author 你好，请问代码是最新的嘛？我记得这个bug我改过了

**Comment by ruan421** [comment]
我觉得网传的结构体，最好还是改成一字节对齐发自我的华为手机-------- 原始邮件 --------主题：Re: [tkzcfc/net_uv] 刚刚发现你的64位校验错误 (#2)发件人：tkzcfc 收件人：tkzcfc/net_uv 抄送：ruan421 ,Author 你好，请问代码是最新的嘛？我记得这个bug我改过了

**Comment by tkzcfc** [comment]
哦哦  好的吧   我空了改下✌(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)✌

**Comment by ruan421** [comment]
还有个问题，kcp传数据的时候，不需要分包，还有一个问题，如何你上层分包了，如果网络不好的时候，需要丢包和控速，那么会导致包不完整，你自己定义的包头并没有标志表示包头包中包尾，还有默认的kcp最多支持255个分片，意思就是如果mtu是1024,那么一个包最大只能到255K，超过就会不完整

**Comment by ruan421** [comment]
你应该是做游戏的，试着用erlang做后台服务器，很有意思的

**Comment by tkzcfc** [comment]
kcp内部做了包序号校验的  如果不自己做分包每次发包就只能很小  超过了kcp的限制大小就会直接被kcp忽略  那个值很小  貌似是千多个字节吧

**Comment by tkzcfc** [comment]
我每次使用kcp发送的最大字节数没有超过1400

**Comment by tkzcfc** [comment]
我并不是做服务器端的  只是个做客户端的😁

**Comment by ruan421** [comment]
不是，你扔进去，256K，他会按照你填 的mtu,kcp也有个mtu，他会自动跟你分

**Comment by tkzcfc** [comment]
有这种操作?我记得之前丢大了使用发送函数直接返回一个错误值给我就完了  根本发都没有发😭

**Comment by ruan421** [comment]
是的

**Comment by ruan421** [comment]
kcp内部的分片大小是u8
超过256K需要修改代码

**Comment by ruan421** [comment]
也就是你扔256K以下的没问题，超过256K就不行了，会给你做掉多的

**Comment by ruan421** [comment]
直接返回-2

**Comment by tkzcfc** [comment]
哦哦  那还是需要自己分片嘛

**Comment by ruan421** [comment]
改下代码就可以了

**Comment by tkzcfc** [comment]
好吧

**Comment by ruan421** [comment]
两种方式，自己分片，如果要控速的话，就要你那个session那儿返回kcp的未发送的数据有多少，如果不分，那么就需要改代码，内部做控制

**Comment by ruan421** [comment]
kcp的缓冲是无限增加的，没有限制

**Comment by tkzcfc** [comment]
嗯嗯   当时先写的tcp  kcp那边就和tcp一个模式的   其实最后写完这个之后感觉这个网络框架被我给限制了  自己加了包头消息校验还有心跳那些   所以后边我有写了套不带这些的tcp

**Comment by ruan421** [comment]
恩，看到了，哥们的代码质量不错，如果是90后，很了不起，很少有人会去思考

**Comment by tkzcfc** [comment]
我后边用这套写了个vpn测试下来感觉tcp和kcp差距也不是好大  可能是网络抖动不明显吧

**Comment by ruan421** [comment]
你这个代码节约了我不少时间，再次感谢，当初我需要设计libuv+kcp，刚好搜到你这个

**Comment by tkzcfc** [comment]
哈哈  老哥这是夸我么  你难道不是90后?

**Comment by ruan421** [comment]
kcp在3g 4g还有wifi下比tcp实时

**Comment by ruan421** [comment]
我是80后，十年工作经验了

**Comment by ruan421** [comment]
如果你在有线的网络条件下，并没有太大的区别

**Comment by tkzcfc** [comment]
厉害  这声大哥我先叫了

**Comment by ruan421** [comment]
因为你没做过流媒体，所以可能感觉不到kcp人优势

**Comment by tkzcfc** [comment]
我是做电脑vpn的  弄到手机上可能差距比较明显吧

**Comment by ruan421** [comment]
有golang写的kcpturn，一堆人拿来做vpn

**Comment by ruan421** [comment]
是的，你搞到手机上就会很明显，

**Comment by tkzcfc** [comment]
嗯嗯

**Comment by ruan421** [comment]
兄弟那里人呀？

**Comment by tkzcfc** [comment]
成都哇  你呢 老哥

**Comment by ruan421** [comment]
加个QQ聊吧，95552817,我是泸州的，在成都上的班，工作了两年来的深圳，以前在川大智胜上过班

**Comment by tkzcfc** [comment]
好的😁

**Comment by ruan421** [comment]
看了你的打洞算法好像还没写

**Comment by tkzcfc** [comment]
打洞写了的  按照我自己的思路来的  弄完之后测了下可以成功  之后就没管过了  主要感觉我用不上  没咋关注
