### ISSUE TITLE
disconnect的时候，如果没连上，直接飞掉

### ISSUE THREAD

**Issue by ruan421** [tkzcfc/net_uv#3]

**Comment by tkzcfc** [comment]
client？？？

**Comment by tkzcfc** [comment]
可以把具体代码给我看看吗？

**Comment by ruan421** [comment]
case TCP_CLI_OP_DISCONNECT:	// 断开连接
		{
			auto sessionData = getClientSessionDataBySessionId(curOperation.sessionID);
			if(sessionData!=NULL)
				{
			if (sessionData->connectState == CONNECT)
			{
				sessionData->connectState = DISCONNECTING;
				sessionData->session->executeDisconnect();
			}
				}
		}break;
断开连接那儿，我加了个判断，就可以了,因为如果没连接的获取的东西是空指针，想当于不对称了

**Comment by tkzcfc** [comment]
嗯嗯 好的 我把代码改下。。
